apiVersion: v1
kind: Service
metadata:
  name: yml-pingme-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
      service_id: ping-server-from-yml
  ports:
  - nodePort: 30080
    port: 8090
    targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: yml-pingme-external-point
  namespace: default
spec:
  type: LoadBalancer
  selector:
      service_id: ping-server-from-yml
  ports:
  - port: 30090
    targetPort: 8090